runtime: python37

automatic_scaling:
  min_instances: 5
  max_instances: 15

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  static_files: index.html
  upload: index.html
